### ISSUE TITLE
Full Stack Capstone Project

### ISSUE THREAD

**Issue by ernest-phillips** [ernest-phillips/Engineer-in-training#1]
## Full stack Capstone  
- [x] Conceptualize a great app
- [x] Brainstorm user stories and features
- [x] Descope
- [ ] HTML wireframes and user flows
- [ ] Static React client
- [ ] Feedback and iteration
- [ ] Implement and test server-side API
- [ ] Complete full version of client
- [ ] Client side tests
- [ ] Final feedback and iteration
- [ ] Documentation and Cleanup

## Fourth mock interview: React and Redux

- [ ] Mock interview: React and Redux
- [ ] Practice mock interview

**Comment by nebiyou-gebretatios** [comment]
Test comment
